/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        brandlight: "var(--brandlight)",
        brandprimary: "var(--brandprimary)",
        brandsecondary: "var(--brandsecondary)",
        errorbg: "var(--errorbg)",
        errorcontent: "var(--errorcontent)",
        errordark: "var(--errordark)",
        issuebg: "var(--issuebg)",
        issuecontent: "var(--issuecontent)",
        neutralbg: "var(--neutralbg)",
        neutralcontent: "var(--neutralcontent)",
        "neutrallight-bg": "var(--neutrallight-bg)",
        neutralstroke: "var(--neutralstroke)",
        "neutralsub-content": "var(--neutralsub-content)",
        neutraltext: "var(--neutraltext)",
        neutralwhite: "var(--neutralwhite)",
        predictionbg: "var(--predictionbg)",
        predictioncontent: "var(--predictioncontent)",
        primarybrand: "var(--primarybrand)",
        scheduledbg: "var(--scheduledbg)",
        scheduledcontent: "var(--scheduledcontent)",
        "sec-text": "var(--sec-text)",
        successbg: "var(--successbg)",
        successcontent: "var(--successcontent)",
        successdark: "var(--successdark)",
        warningbg: "var(--warningbg)",
        warningcontent: "var(--warningcontent)",
      },
      fontFamily: {
        "text-base-medium": "var(--text-base-medium-font-family)",
        "text-base-regular": "var(--text-base-regular-font-family)",
        "text-base-semibold": "var(--text-base-semibold-font-family)",
        "text-heading-h5": "var(--text-heading-h5-font-family)",
        "text-SM-normal": "var(--text-SM-normal-font-family)",
        "text-small-medium": "var(--text-small-medium-font-family)",
        "text-small-regular": "var(--text-small-regular-font-family)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
